version: "3.8"

services:
    openelevation:
        restart: always
        image: openelevation/open-elevation
        volumes:
            - "./data:/code/data"
            - "./certs:/code/certs"
        environment:
            - PYTHONUNBUFFERED=1
        command: stdbuf -i0 -o0 -e0 python3 server.py
        networks:
            - arvee-backend_sail
        ports:
            - 8080:8080
networks:
    arvee-backend_sail:
        external: true
